-- 11. 인덱스 : 주 키가 아닌 필드를 중심으로 질의를 많이 하는 경우 (SELECT) 조회 속도 향상을 위해 씀

SELECT * FROM USER_INDEXES; --SCOTT 계정의 소유한 인덱스 

DROP TABLE EMP01;

CREATE TABLE EMP01
    AS SELECT * FROM EMP;

INSERT INTO EMP01 SELECT * FROM EMP01; -- 1번 실행시 (28개가 됨) , 2번 실행시 (56개) .... 

SELECT COUNT(*) FROM EMP01;

INSERT INTO EMP01 SELECT * FROM EMP01; --12번 실행 (22만개)
INSERT INTO EMP01 (EMPNO, ENAME, DEPTNO) VALUES (1111,'HONG',40);
INSERT INTO EMP01 SELECT * FROM EMP01;  --총 대략 180만개 생성 

--인덱스 생성 전 조회 속도 : 0.04초 
SELECT * FROM EMP01 WHERE ENAME = 'HONG';
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME); --인덱스 생성 
--인덱스 생성 후 조회 :0.018초
SELECT * FROM EMP01 WHERE ENAME = 'HONG';
SELECT * FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EMP01_ENAME';
DROP INDEX IDX_EMP01_ENAME;


