DROP TABLE STUDENT;
DROP TABLE MAJOR; 
DROP SEQUENCE STUDENT_SEQUENCE_sNO;

-- 테이블, 시퀀스 생성 
CREATE TABLE MAJOR(
    mNO NUMBER(2) NOT NULL PRIMARY KEY,
    mNAME VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE STUDENT_SEQUENCE_sNO
    NOCACHE
    NOCYCLE; 
    
CREATE TABLE STUDENT(
    sNO VARCHAR2(10) NOT NULL PRIMARY KEY, 
    sNAME VARCHAR2(30) NOT NULL,
    SCORE NUMBER(3) CHECK (SCORE BETWEEN 0 AND 100),
    sEXPEL NUMBER(1) DEFAULT 0 CHECK(sEXPEL IN (0,1)), 
    mNO REFERENCES MAJOR(mNO)
); 

SELECT * FROM STUDENT;

-- 데이터 INSERT 
INSERT INTO MAJOR VALUES(1,'빅데이터학'); 
INSERT INTO MAJOR VALUES(2,'기계공학');
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY')||TRIM(TO_CHAR(STUDENT_SEQUENCE_sNO.NEXTVAL,'000')), '김춘자',90,0,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY')||TRIM(TO_CHAR(STUDENT_SEQUENCE_sNO.NEXTVAL,'000')), '고세현',95,0,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY')||TRIM(TO_CHAR(STUDENT_SEQUENCE_sNO.NEXTVAL,'000')), '홍길동',98,0,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY')||TRIM(TO_CHAR(STUDENT_SEQUENCE_sNO.NEXTVAL,'000')), '김길자',98,1,1);

-- 전공 리스트 가져오기 
SELECT mNAME FROM MAJOR;  

-- 학번으로 학생 정보 검색하기 
SELECT sNO,sName,mName,score FROM STUDENT S, MAJOR M WHERE S.mNo = M.mNo AND sNO = 2021002;

-- 이름으로 학생 정보 가져오기 
SELECT sNO,sNAME, SCORE, mNAME FROM STUDENT S, MAJOR M WHERE S.mNo = M.mNo AND sNAME = '홍길동';

-- 전공명으로 학생 정보 검색하기
SELECT ROWNUM "RANK", sName||'('||sNO||')' "sName", SCORE
    FROM (SELECT * FROM STUDENT S, MAJOR M WHERE S.mNO = M.mNO AND S.mNo=1 ORDER BY SCORE DESC);

-- 학생 정보 수정하기 
UPDATE STUDENT SET sNAME = '김세현',SCORE = 98,mNo=2 WHERE sNo=2021002;


-- 모든 학생 정보 출력 하기 
SELECT ROWNUM "RANK",sNAME||'('||sNO||')' "sNAME",mNAME||'('||mNO||')' "mNAME",SCORE 
    FROM (SELECT S.*,M.mNAME FROM STUDENT S, MAJOR M WHERE S.mNO = M.mNO ORDER BY SCORE DESC);

-- 제적된 학생 출력하기 
SELECT ROWNUM "RANK",sNAME||'('||sNO||')' "sNAME",mNAME||'('||mNO||')' "mNAME",SCORE 
    FROM (SELECT S.*,M.mNAME FROM STUDENT S, MAJOR M WHERE S.mNO = M.mNO AND sEXPEL = 1 ORDER BY SCORE);

-- 학생 제적 처리하기
UPDATE STUDENT SET sEXPEL = 1 WHERE sNO = 2021001;
