-- 12장. 트랜잭션 명령어(DML 명령어) : COMMIT, ROLLBACK, SAVEPOINT -> 취소불가 

COMMIT; --새로운 트랜잭션 시작 (INSERT, UPDATE, DELETE 작업 새로 추가될 예정) 
DROP TABLE DEPT01; 
CREATE TABLE DEPT01 AS SELECT * FROM DEPT; 
DESC DEPT01;

SELECT * FROM DEPT01; -- 10,20,30,40번 부서. SELECT 같은 조회만 했을 땐 트랜잭션이 차지 않음 
DELETE FROM DEPT01 WHERE DEPTNO = 40; 
SELECT * FROM DEPT01; --10,20,30번 부서만
ROLLBACK; 
--ROLLBACK 이후 새로운 트랜잭션이 시작됨 
SELECT* FROM DEPT01; --40번 부서 다시 생겨남. 총 10,20,30,40번 부서 
DELETE FROM DEPT01 WHERE DEPTNO = 40;
SELECT * FROM DEPT01;
COMMIT;
--새로운 트랜잭션 시작 
SELECT * FROM DEPT01; --10,20,30번 부서 
DELETE FROM DEPT01 WHERE DEPTNO = 30;
SELECT * FROM DEPT01; --10,20번만 있음
SAVEPOINT C1; --C1지점: 10번, 20번만 있음 
DELETE FROM DEPT01 WHERE DEPTNO =20; 
SELECT * FROM DEPT01; --10번 부서 
SAVEPOINT C2; -- C2 지점 생성 : 10번 부서만 있는 지점
DELETE FROM DEPT01 WHERE DEPTNO= 10;
SELECT * FROM DEPT01; 
ROLLBACK TO C2; -- ROLLBACK; 모두 삭제, ROLLBACK TO C2 -> C2지점으로 돌아감 
COMMIT;