-- ★ 총 연습문제
--1. 사원테이블에서 가장 먼저 입사한 사람의 이름, 급여, 입사일
SELECT ENAME, SAL,(SELECT MIN(HIREDATE) FROM EMP) AS DATE_HIRED FROM EMP;

-- 2. 회사에서 가장 급여가 적은 사람의 이름, 급여
SELECT ENAME, (SELECT MIN(SAL) FROM EMP) AS MIN_SAL FROM EMP;

--5. SCOTT보다 먼저 입사한 사람의 이름, 급여, 입사일, 급여 등급
SELECT ENAME, SAL,HIREDATE, GRADE FROM EMP E, SALGRADE S
    WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT')
        AND SAL BETWEEN LOSAL AND HISAL;

--7. BLAKE 보다 급여가 많은 사원들의 사번, 이름, 급여
SELECT EMPNO, ENAME, SAL FROM EMP
    WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');

--11.  응용심화. CLARK와 같은 부서명이며, 사번이 7698인 직원의 급여보다 많은 급여를 받는 사원들의 사번, 이름, 급여
SELECT EMPNO, ENAME, SAL FROM EMP
    WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='CLARK')AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7698); 


-- 여기서부터는 다중행서브쿼리와 단일행서브쿼리, 이전은 단일행서브쿼리
-- 14.  이름에 “T”가 있는 사원이 근무하는 부서에서 근무하는 모든 직원의 사원 번호,이름,급여(단 사번 순 출력)
SELECT EMPNO, ENAME, SAL FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%T%');

-- 16. EMP 테이블에서 King에게 보고하는 모든 사원의 이름과 급여
SELECT ENAME, SAL FROM EMP
    WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');

-- 17. SALES부서 사원의 이름, 업무
SELECT ENAME, JOB FROM EMP
    WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

-- 18. 월급이 부서 30의 최저 월급보다 높은 사원의 모든 필드
SELECT * FROM EMP
    WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO =30);

-- 19. 부서 10에서 부서 30의 사원과 같은 업무를 맡고 있는 사원의 이름과 업무
SELECT ENAME, JOB FROM EMP WHERE DEPTNO =10 AND JOB IN (SELECT JOB FROM EMP WHERE DEPTNO=30);

-- 20.  FORD와 업무도 월급도 같은 사원의 모든 필드
SELECT * FROM EMP WHERE (JOB, SAL) = (SELECT JOB, SAL FROM EMP WHERE ENAME ='FORD');

-- 22. SCOTT 또는 WARD와 월급이 같은 사원의 정보를 이름,업무,급여
SELECT ENAME, JOB, SAL
    FROM EMP 
    WHERE SAL IN (SELECT SAL FROM EMP WHERE ENAME IN ('SCOTT','WARD'));

-- 23. CHICAGO에서 근무하는 사원과 같은 업무를 하는 사원들의 이름,업무
SELECT ENAME, JOB FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND LOC = (SELECT LOC FROM DEPT WHERE LOC = 'CHICAGO');

-- 24. 부서별로 월급이 평균 월급보다 높은 사원을 사번, 이름, 급여
SELECT EMPNO, ENAME, SAL FROM EMP E
    WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO = E.DEPTNO GROUP BY DEPTNO); 

-- 26. 적어도 한 명 이상으로부터 보고를 받을 수 있는 사원을 업무, 이름, 사번, 부서번호를 출력(단, 부서번호 순으로 오름차순 정렬)
SELECT DISTINCT MANAGER.JOB, MANAGER.ENAME, MANAGER.EMPNO, MANAGER.DEPTNO FROM EMP WORKER, EMP MANAGER
    WHERE WORKER.MGR(+) = MANAGER.EMPNO AND WORKER.EMPNO IS NOT NULL; 

-- 27.  말단 사원의 사번, 이름, 업무, 부서번호
SELECT E2.EMPNO, E2.ENAME, E2.JOB, E2.DEPTNO FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO AND E1.MGR IS NULL; 