--8장. SEQUENCE: 순차 번호 생성기, SEQUENCE는 인위적인 PRIMARY KEY 사용 용도 
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1 
    MAXVALUE 9999 --PRIMARY KEY 필드의 타입에 맞게 입력한다  
    MINVALUE 1
    NOCACHE -- 왠만하면 필수. 서버를 껐다가 키는 경우를 대비해서 
    NOCYCLE; -- 이것도 왠만하면 필수. 중복된 PRIMARY KEY 생성되는걸 원치 않으므로;

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY, --시퀀스 이용
    NAME VARCHAR2(30) NOT NULL, 
    TEL VARCHAR2(20) UNIQUE, 
    ADDRESS VARCHAR2(100),
    LAST_MODIFIED DATE DEFAULT SYSDATE
);

INSERT INTO FRIEND (NUM,NAME,TEL, ADDRESS) --SEQ.NEXTVAL 증가된 값을 계속 가져옴
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동',NULL,'서울시 마포구'); 
INSERT INTO FRIEND (NUM,NAME,TEL, ADDRESS) --SEQ.NEXTVAL 증가된 값을 계속 가져옴
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동','010-9999-9999','서울시 서대문구');
INSERT INTO FRIEND (NUM,NAME,TEL, ADDRESS) --SEQ.NEXTVAL 증가된 값을 계속 가져옴
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동','010-8888-8888','서울시 영등포구'); 
    
SELECT * FROM FRIEND; --에러가 나서 데이터가 못들어가도 시퀀스 값은 이미 증가되어있음
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값 확인용도 .CURRVAL
COMMIT;


--간단한 예제
DROP SEQUENCE TEST_SEQ;
CREATE SEQUENCE TEST_SEQ 
    START WITH 101
    INCREMENT BY 10
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;
